#!/usr/bin/sh

# Verificando argumentos.
if [ -z $1 ]
then
  echo "Requires argument."
  exit 1
fi

# Verificando se o usuario esta logado como root
if [ `id -u` != 0 ]
then
  echo "This is script needs to be run as root."
  exit 1
fi 

# Verificando se o arquivo existe ou não
ls -lA $1 >> /dev/null
if [ $? != 0 ]
then
  echo "No such file directory."
  exit 1
fi

# Criando diretorio temporario
echo "Making directory temp..."
mkdir temp

#Entrando em temp em movendo deb para lá
mv $1 temp
cd temp

#Descompctando deb.
echo "Unpacking deb file"
ar x $1

mv $1 .. #Movendo deb original para fora da pasta temp.

echo "Unpacking control.tar.xz"
tar -xvf control.tar.* >> ../log_file.log
if [ $? != 0 ]
then
  echo "An error has occured, the file $1 may be corrupt."
  mv $1 ..
  cd ..
  sudo rm -rf temp/
  exit 1
fi

# Pegando caracteristicas do .deb, apartir do control.tar
name_package=`cat control | grep Package | cut -d " " -f 2`
requires_package=`cat control | grep Depends | cut -d " " -f 2`

echo "Unpacking data.tar.xz"
tar xvf data.tar.* >> ../log_file.log
if [ $? != 0 ]
then
  echo "An error has occured, the file $1 may be corrupt."
  mv $1 ..
  cd ..
  sudo rm -rf temp/
  exit 1
fi

echo "Depends $requires_package"
read -p "Are you sure you want to continue?[Y/n]" esc
if [ "$esc" = "n" ] || [ "$esc" = "N" ] ; then
  echo "OK bye bye"
  echo 0
fi

# Copiando todo o diretorio de data.tar.xz para o /, o que termina o processo do instalação.
echo "Installing $name_package"
sudo cp -R ./* /

# Apagando /temp, é log_file.log
cd ..
sudo rm -rf ./temp
sudo rm ./log_file.log
